name: 'Setup Node.js'
description: 'Setup Node.js with consistent version and npm caching'
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
