// Environment Configuration
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by build-config.js
//
// Use this to detect the current environment in your application

window.APP_CONFIG = window.APP_CONFIG || {};
window.APP_CONFIG.environment = 'testing';
window.APP_CONFIG.baseUrl = '/Eisenhauer/testing/';
window.APP_CONFIG.isProd = false;
window.APP_CONFIG.isStaging = false;
window.APP_CONFIG.isTesting = true;

// Export for module usage
const environment = {
    env: 'testing',
    baseUrl: '/Eisenhauer/testing/',
    isProd: false,
    isStaging: false,
    isTesting: true
};

console.log('🌍 App Environment:', environment.env);
console.log('🔗 Base URL:', environment.baseUrl);
