// Firebase Configuration
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by build-config.js from .env.testing
//
// Environment: testing
// Base URL: /Eisenhauer/testing/
//
// SECURITY NOTE:
// Firebase web API keys are designed to be public (client-side keys).
// Your app's security is enforced through:
// 1. ✅ Firebase Security Rules (Firestore/Storage/Database)
// 2. ✅ Authorized domains in Firebase Console
// 3. ✅ Optional: Firebase App Check for additional protection
//
// These client-side keys are NOT secret. They identify your Firebase project
// and are meant to be included in client applications.
//
// Learn more: https://firebase.google.com/docs/projects/api-keys

const firebaseConfig = {
    apiKey: "AIzaSyCPRToNyAwdAxHz4d1W9d3_mJKugAwJ_kM",
    authDomain: "eisenhauer-testing.firebaseapp.com",
    projectId: "eisenhauer-testing",
    storageBucket: "eisenhauer-testing.firebasestorage.app",
    messagingSenderId: "850919553916",
    appId: "1:850919553916:web:b959052ede9e2aa736c2f9",
    measurementId: "G-TESTING-NO-ANALYTICS"
};

// Firebase initialisieren
firebase.initializeApp(firebaseConfig);

// Firebase Services
const auth = firebase.auth();
const db = firebase.firestore();

// Auth Provider
const googleProvider = new firebase.auth.GoogleAuthProvider();
googleProvider.setCustomParameters({
    prompt: 'select_account'
});

const appleProvider = new firebase.auth.OAuthProvider('apple.com');

// Optional: Offline-Persistenz aktivieren
db.enablePersistence()
    .catch((err) => {
        if (err.code == 'failed-precondition') {
            console.log('Persistence can only be enabled in one tab at a time.');
        } else if (err.code == 'unimplemented') {
            console.log('The current browser does not support persistence.');
        }
    });
